services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
      - ~/.config/zed:/app/.zed/
    tty: true
    image: hono-app-boilerplate
    container_name: hono-app-boilerplate
    environment:
      TZ: "Asia/Tokyo"
